# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# relative_permalinks: true
permalink:           pretty

# Setup
title:               Martian'S Blog
tagline:             '流年不利是本命'
description:         '半碗茗香半盏杯，半游江湖半思归。半随潮流半念北，半自奋起半意颓。'
url:                 https://martian101.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              zqzhao5
  url:               https://twitter.com/zqzhao5
  email:             zqzhao5@gmail.com

# Custom vars
version:             1.0.0
markdown: redcarpet
gems: [jekyll-paginate, jekyll-gist]
# Build settings
markdown: kramdown
theme: lanyon
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
