# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# relative_permalinks: true
permalink:           pretty

# Setup
title:               Martian'S Blog
tagline:             '穷诸玄辨，若一毫置于太虚；竭世枢机，似一滴投于巨壑'
description:         '半碗茗香半盏杯，<br>半游江湖半思归。<br>半随潮流半念北，<br>半自奋起半意颓。'
url:                 https://martian101.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              zqzhao5
  url:               https://twitter.com/zqzhao5
  email:             zqzhao5@gmail.com

# Custom vars
version:             1.0.0
markdown: redcarpet
gems: [jekyll-paginate, jekyll-gist]
# Build settings
markdown: kramdown
theme: lanyon
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
